### ISSUE TITLE
App crash after play / stop a couple of times

### ISSUE THREAD

**Issue by netmikey** [frontyard/cordova-plugin-exoplayer#18]
While stress-testing our app, we noticed some strange behaviour from the ExoPlayer plugin: when I continuously stop / play an aac stream, sometimes I end up with the stream playing twice (though I'm sure I explicitly call `close()` on the previously running player. Sometimes it seems that a `close()` call gets lost, other times it seems that the same stream is started twice in a row (really quickly, so I get some kind of comb filtering effect going...).

When I am in the situation where the player is playing multiple streams at once, a couple of play / stop's more and the app ends up crashing. I managed to capture a stack trace from that crash, I hope this can help:

```
05-23 21:44:13.318: E/AndroidRuntime(21329): FATAL EXCEPTION: main
05-23 21:44:13.318: E/AndroidRuntime(21329): Process: com.MyPlayer, PID: 21329
05-23 21:44:13.318: E/AndroidRuntime(21329): java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.exoplayer2.SimpleExoPlayer.prepare(com.google.android.exoplayer2.source.MediaSource)' on a null object reference
05-23 21:44:13.318: E/AndroidRuntime(21329): 	at co.frontyard.cordova.plugin.exoplayer.Player.preparePlayer(Player.java:225)
05-23 21:44:13.318: E/AndroidRuntime(21329): 	at co.frontyard.cordova.plugin.exoplayer.Player.createPlayer(Player.java:174)
05-23 21:44:13.318: E/AndroidRuntime(21329): 	at co.frontyard.cordova.plugin.exoplayer.Plugin$1.run(Plugin.java:44)
05-23 21:44:13.318: E/AndroidRuntime(21329): 	at android.os.Handler.handleCallback(Handler.java:815)
05-23 21:44:13.318: E/AndroidRuntime(21329): 	at android.os.Handler.dispatchMessage(Handler.java:104)
05-23 21:44:13.318: E/AndroidRuntime(21329): 	at android.os.Looper.loop(Looper.java:207)
05-23 21:44:13.318: E/AndroidRuntime(21329): 	at android.app.ActivityThread.main(ActivityThread.java:5728)
05-23 21:44:13.318: E/AndroidRuntime(21329): 	at java.lang.reflect.Method.invoke(Native Method)
05-23 21:44:13.318: E/AndroidRuntime(21329): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
05-23 21:44:13.318: E/AndroidRuntime(21329): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
```

As a reference, here's my player-related code (this is TypeScript, but the exoplayer calls should be clear):

```
  private player: any;

  public playerPlay(url: string): void {
    if (this.player) {
      // Dismiss existing player
      this.playerStop();
    }

    // Create new player
    this.player = exoplayer.init({
        url: url,
        audioOnly: true,
    });
    this.player.show();
  }

  public playerStop(): void {
    if (this.player) {
      this.player.close();
      this.player = null;
    }
  }
```

With this code, I then call `playerPlay(someUrl)` a couple of times. As you can see, there should never be more than one player playing at a time. Since JavaScript is single threaded, my wild guess would be a race condition in the Java part of the exoplayer-plugin?

**Comment by frontyard** [comment]
@netmikey I released version 2.3.0 which changes how the instance of the plugin is handled. Can you try and replicate this issue with this version and we'll take it from there?

**Comment by netmikey** [comment]
Thanks for putting effort into this! :)

Unfortunately, it seems that the new version `2.3.0` doesn't solve the issue. I'm still hearing multiple streams when switching streams (that issue feels like it's gotten even worse, but that might be subjective), and the app still crashes when stress-testing it. Here is the stack trace on version 2.3.0:

```
05-24 18:05:29.431: E/AndroidRuntime(27486): FATAL EXCEPTION: main
05-24 18:05:29.431: E/AndroidRuntime(27486): Process: com.MyPlayer, PID: 27486
05-24 18:05:29.431: E/AndroidRuntime(27486): java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.exoplayer2.SimpleExoPlayer.prepare(com.google.android.exoplayer2.source.MediaSource)' on a null object reference
05-24 18:05:29.431: E/AndroidRuntime(27486): 	at co.frontyard.cordova.plugin.exoplayer.Player.preparePlayer(Player.java:226)
05-24 18:05:29.431: E/AndroidRuntime(27486): 	at co.frontyard.cordova.plugin.exoplayer.Player.createPlayer(Player.java:175)
05-24 18:05:29.431: E/AndroidRuntime(27486): 	at co.frontyard.cordova.plugin.exoplayer.Plugin$1.run(Plugin.java:44)
05-24 18:05:29.431: E/AndroidRuntime(27486): 	at android.os.Handler.handleCallback(Handler.java:815)
05-24 18:05:29.431: E/AndroidRuntime(27486): 	at android.os.Handler.dispatchMessage(Handler.java:104)
05-24 18:05:29.431: E/AndroidRuntime(27486): 	at android.os.Looper.loop(Looper.java:207)
05-24 18:05:29.431: E/AndroidRuntime(27486): 	at android.app.ActivityThread.main(ActivityThread.java:5728)
05-24 18:05:29.431: E/AndroidRuntime(27486): 	at java.lang.reflect.Method.invoke(Native Method)
05-24 18:05:29.431: E/AndroidRuntime(27486): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
05-24 18:05:29.431: E/AndroidRuntime(27486): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
```

Not that in my case, I cannot use the new `setStream(url, controllerConfig)` method, so I'm still basically doing:

```
    ExoPlayer.close();
    ExoPlayer.show({
        url: url,
        audioOnly: true,
    }, event => this.onSuccess(event));
```

... but I guess it should work this way too, shouldn't it?

**Comment by frontyard** [comment]
@netmikey I wasn't expecting the problem to go away, it's just more difficult to debug if we're on different versions.

Let me first ask you why can't you use setStream?

Looking at the exception above, I'm not 100% what exactly is null. The offending line is
`exoPlayer.prepare(mediaSource);`

exoPlayer instance comes from ExoPlayer: 
`exoPlayer = ExoPlayerFactory.newSimpleInstance(this.activity, trackSelector, loadControl);`

I can put an extra check but I don't see why either exoPlayer or mediaSource would be null.

I'm suspecting calling .close and .show in rapid succession is causing some things to not get initialized in time.

**Comment by netmikey** [comment]
I cannot use `setStream` because exoplayer is just one of multiple player backends in our project (for example, we have an html5-based player for the browser), and setting the stream into a "running" player isn't something a player API usually offers, so I cannot use it in an abstract way for all player backends.

I just had a deeper look at your implementation and I think I might have found what's happening:

In line 214, in the `preparePlayer()` method, you're initializing the `exoPlayer` variable to a new player instance. And in Line 298, in the `close()` method, you're resetting the `exoPlayer` variable to `null`. Now you have to keep in mind that calls will probably land concurrently on that `co.frontyard.cordova.plugin.exoplayer.Player` instance. So if one thread is running through `preparePlayer()` while another is executing `stop()`, line 298 might be executed right after line 214, causing the NPE when execution arrives at line 226. I think you'll probably have to save yourself from state corruption, e.g. by synchronising each access to your local variables, especially the `exoPlayer` one.

This concurrency issue is probably also the reason why we're seeing multiple streams running in parallel in our stress test. So my guess is that fixing it will solve both issues at once :-)

**Comment by frontyard** [comment]
@netmikey that was great help!

I realized, unlike all other methods, `close` is not being called on the UI thread. I released version 2.3.1 that should fix this issue.

**Comment by netmikey** [comment]
You're welcome! :)

And yes I can confirm: I'm unable to reproduce the errors described above, looks like 2.3.1 fixes it all. Thanks again for your support! 👍
